In [1]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# with minimum dimensions
c = np.array([[1,2,3,4,5],[7,8,9,0,9]], ndmin = 3)
print(c)

[[[1 2 3 4 5]
  [7 8 9 0 9]]]


In [19]:
# datatype parameter
d = np.array([1,2,3,4,5], dtype=complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [21]:
# Shape
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [26]:
# Resize the array
a.resize(3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
# an array of evenly spaced numbers
b = np.arange(24)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [40]:
# b is 1 dimensional array
# reshape it
b = b.reshape(2, 4, 3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [42]:
# The example of an empty array
a = np.empty([3,2], dtype = int)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
# The example of array of zeroes 
# Syntax = numpy.zeros(shape, dtype = float, order = 'C')

a = np.zeros([3, 3], dtype = int)
print(a)
print('next')
a = np.append(a, np.array([[0,0,0]]), axis=0)
print(a)
print('next')
a = np.append(a, np.array([[0], [0], [0], [0]]), axis=1)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
next
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
next
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
# Array filled with ones
# Syntax = numpy.ones(shape, dtype = None, order = 'C')

a = np.ones([3,3], dtype = int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [48]:
# Arange function
# np.arange(start, stop, step, dtype)

a = np.arange(0, 100, 2, dtype=int)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [65]:
a = a.reshape(50,1)
print(a)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]
 [52]
 [54]
 [56]
 [58]
 [60]
 [62]
 [64]
 [66]
 [68]
 [70]
 [72]
 [74]
 [76]
 [78]
 [80]
 [82]
 [84]
 [86]
 [88]
 [90]
 [92]
 [94]
 [96]
 [98]]


In [66]:
# numpy.linspace
# This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

# numpy.linspace(start, stop, num, endpoint, retstep, dtype)

a = np.linspace(1, 100, 55)
print(a)

[  1.           2.83333333   4.66666667   6.5          8.33333333
  10.16666667  12.          13.83333333  15.66666667  17.5
  19.33333333  21.16666667  23.          24.83333333  26.66666667
  28.5         30.33333333  32.16666667  34.          35.83333333
  37.66666667  39.5         41.33333333  43.16666667  45.
  46.83333333  48.66666667  50.5         52.33333333  54.16666667
  56.          57.83333333  59.66666667  61.5         63.33333333
  65.16666667  67.          68.83333333  70.66666667  72.5
  74.33333333  76.16666667  78.          79.83333333  81.66666667
  83.5         85.33333333  87.16666667  89.          90.83333333
  92.66666667  94.5         96.33333333  98.16666667 100.        ]


In [67]:
print(a.size)

55


In [68]:
a = a.reshape(55, 1)
print(a)

[[  1.        ]
 [  2.83333333]
 [  4.66666667]
 [  6.5       ]
 [  8.33333333]
 [ 10.16666667]
 [ 12.        ]
 [ 13.83333333]
 [ 15.66666667]
 [ 17.5       ]
 [ 19.33333333]
 [ 21.16666667]
 [ 23.        ]
 [ 24.83333333]
 [ 26.66666667]
 [ 28.5       ]
 [ 30.33333333]
 [ 32.16666667]
 [ 34.        ]
 [ 35.83333333]
 [ 37.66666667]
 [ 39.5       ]
 [ 41.33333333]
 [ 43.16666667]
 [ 45.        ]
 [ 46.83333333]
 [ 48.66666667]
 [ 50.5       ]
 [ 52.33333333]
 [ 54.16666667]
 [ 56.        ]
 [ 57.83333333]
 [ 59.66666667]
 [ 61.5       ]
 [ 63.33333333]
 [ 65.16666667]
 [ 67.        ]
 [ 68.83333333]
 [ 70.66666667]
 [ 72.5       ]
 [ 74.33333333]
 [ 76.16666667]
 [ 78.        ]
 [ 79.83333333]
 [ 81.66666667]
 [ 83.5       ]
 [ 85.33333333]
 [ 87.16666667]
 [ 89.        ]
 [ 90.83333333]
 [ 92.66666667]
 [ 94.5       ]
 [ 96.33333333]
 [ 98.16666667]
 [100.        ]]


In [69]:
# numpy.logspace
# This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. 
# Start and stop endpoints of the scale are indices of the base, usually 10.

# # numpy.logspace(start, stop, num, endpoint, base, dtype)
# num
# The number of values between the range. Default is 50

n = np.logspace(1, 100, num = 70)
print(n)

[1.00000000e+001 2.72133877e+002 7.40568469e+003 2.01533769e+005
 5.48441658e+006 1.49249555e+008 4.06158599e+009 1.10529514e+011
 3.00788252e+012 8.18546731e+013 2.22754295e+015 6.06189899e+016
 1.64964807e+018 4.48925126e+019 1.22167735e+021 3.32459793e+022
 9.04735724e+023 2.46209240e+025 6.70018750e+026 1.82334800e+028
 4.96194760e+029 1.35031404e+031 3.67466194e+032 1.00000000e+034
 2.72133877e+035 7.40568469e+036 2.01533769e+038 5.48441658e+039
 1.49249555e+041 4.06158599e+042 1.10529514e+044 3.00788252e+045
 8.18546731e+046 2.22754295e+048 6.06189899e+049 1.64964807e+051
 4.48925126e+052 1.22167735e+054 3.32459793e+055 9.04735724e+056
 2.46209240e+058 6.70018750e+059 1.82334800e+061 4.96194760e+062
 1.35031404e+064 3.67466194e+065 1.00000000e+067 2.72133877e+068
 7.40568469e+069 2.01533769e+071 5.48441658e+072 1.49249555e+074
 4.06158599e+075 1.10529514e+077 3.00788252e+078 8.18546731e+079
 2.22754295e+081 6.06189899e+082 1.64964807e+084 4.48925126e+085
 1.22167735e+087 3.324597

In [74]:
# print values of a 2D array
a = np.arange(1, 21)
a = a.reshape(4, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [76]:
for i in a:
    print(i)
    print('hi')

[1 2 3 4 5]
hi
[ 6  7  8  9 10]
hi
[11 12 13 14 15]
hi
[16 17 18 19 20]
hi


In [77]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [78]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [85]:
a = a.reshape(4, 5, 1)
print(a)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]


In [98]:
a = a.reshape(4, 5)
print(a)
print(a[3][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20
